version: '3.8'

services:
  ww3-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: ww3-dashboard-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ACLED_API_KEY=${ACLED_API_KEY}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount logs directory
      - ./logs:/app/logs
    networks:
      - ww3-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: ww3-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - ww3-dashboard
    networks:
      - ww3-network
    profiles:
      - with-nginx

networks:
  ww3-network:
    driver: bridge

volumes:
  logs:
    driver: local 